export const galleryFiles = [
  {
    name: "IMG_3006.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3006.jpg",
    meta: { iso: "100", shutter: "1/125", aperture: "f/11", loc: "Paris" },
  },
  {
    name: "IMG_3153.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3153.jpg",
    meta: { iso: "200", shutter: "1/250", aperture: "f/10", loc: "Park Versaille" },
  },
  {
    name: "IMG_3338.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3338.jpg",
    meta: { iso: "100", shutter: "1/320", aperture: "f/11", loc: "Clouds" },
  },
  {
    name: "IMG_3360.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3360.jpg",
    meta: { iso: "100", shutter: "1/200", aperture: "f/9", loc: "Warsaw" },
  },
  {
    name: "IMG_3438.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3438.jpg",
    meta: { iso: "320", shutter: "1/80", aperture: "f/4.5", loc: "Studio" },
  },
  {
    name: "IMG_3439.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3439.jpg",
    meta: { iso: "100", shutter: "1/125", aperture: "f/8", loc: "Warsaw" },
  },
  {
    name: "IMG_3523.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3523.jpg",
    meta: { iso: "100", shutter: "1/500", aperture: "f/5.6", loc: "Warsaw" },
  },
  {
    name: "IMG_3662.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3662.jpg",
    meta: { iso: "400", shutter: "1/500", aperture: "f/8.0", loc: "Kraków" },
  },
  {
    name: "IMG_3846.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_3846.jpg",
    meta: { iso: "160", shutter: "1/80", aperture: "f/5.6", loc: "Landscape" },
  },
  // Fixed the data up till this point 
  {
    name: "IMG_5775.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_5775.jpg",
    meta: { iso: "800", shutter: "1/1000", aperture: "f/4.0", loc: "Action" },
  },
  {
    name: "IMG_5860.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_5860.jpg",
    meta: { iso: "100", shutter: "1/100", aperture: "f/11", loc: "Macro" },
  },
  {
    name: "IMG_5884.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_5884.jpg",
    meta: { iso: "400", shutter: "1/320", aperture: "f/2.0", loc: "Street" },
  },
  {
    name: "IMG_6100.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6100.jpg",
    meta: { iso: "1250", shutter: "1/60", aperture: "f/1.8", loc: "Interior" },
  },
  {
    name: "IMG_6157.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6157.jpg",
    meta: { iso: "200", shutter: "1/400", aperture: "f/5.6", loc: "Nature" },
  },
  {
    name: "IMG_6200.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6200.jpg",
    meta: { iso: "100", shutter: "1/2000", aperture: "f/2.8", loc: "Bright" },
  },
  {
    name: "IMG_6260.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6260.jpg",
    meta: { iso: "800", shutter: "1/125", aperture: "f/4.0", loc: "Cloudy" },
  },
  {
    name: "IMG_6266.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6266.jpg",
    meta: { iso: "1600", shutter: "1/60", aperture: "f/2.8", loc: "Indoor" },
  },
  {
    name: "IMG_6282.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6282.jpg",
    meta: { iso: "100", shutter: "1/250", aperture: "f/8.0", loc: "Arch" },
  },
  {
    name: "IMG_6363.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6363.jpg",
    meta: { iso: "400", shutter: "1/500", aperture: "f/4.0", loc: "Sport" },
  },
  {
    name: "IMG_6431.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6431.jpg",
    meta: { iso: "200", shutter: "1/160", aperture: "f/1.8", loc: "Candid" },
  },
  {
    name: "IMG_6470.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6470.jpg",
    meta: { iso: "100", shutter: "1/400", aperture: "f/5.6", loc: "Daylight" },
  },
  {
    name: "IMG_6481.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6481.jpg",
    meta: { iso: "800", shutter: "1/60", aperture: "f/2.0", loc: "Evening" },
  },
  {
    name: "IMG_6539.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6539.jpg",
    meta: { iso: "3200", shutter: "1/30", aperture: "f/1.4", loc: "Dark" },
  },
  {
    name: "IMG_6540.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6540.jpg",
    meta: { iso: "3200", shutter: "1/30", aperture: "f/1.4", loc: "Dark" },
  },
  {
    name: "IMG_6647.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6647.jpg",
    meta: { iso: "200", shutter: "1/200", aperture: "f/8.0", loc: "Flash" },
  },
  {
    name: "IMG_6652.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6652.jpg",
    meta: { iso: "200", shutter: "1/200", aperture: "f/8.0", loc: "Flash" },
  },
  {
    name: "IMG_6661.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6661.jpg",
    meta: { iso: "400", shutter: "1/100", aperture: "f/4.0", loc: "Detail" },
  },
  {
    name: "IMG_6680.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6680.jpg",
    meta: { iso: "100", shutter: "1/640", aperture: "f/2.8", loc: "Outside" },
  },
  {
    name: "IMG_6701.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6701.jpg",
    meta: { iso: "800", shutter: "1/2000", aperture: "f/4.0", loc: "Motion" },
  },
  {
    name: "IMG_6725.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6725.jpg",
    meta: { iso: "100", shutter: "1/125", aperture: "f/11", loc: "Scenery" },
  },
  {
    name: "IMG_6729.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6729.jpg",
    meta: { iso: "100", shutter: "1/125", aperture: "f/11", loc: "Scenery" },
  },
  {
    name: "IMG_6732.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6732.jpg",
    meta: { iso: "100", shutter: "1/125", aperture: "f/11", loc: "Scenery" },
  },
  {
    name: "IMG_6940.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6940.jpg",
    meta: { iso: "1600", shutter: "1/50", aperture: "f/2.0", loc: "Event" },
  },
  {
    name: "IMG_6944.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6944.jpg",
    meta: { iso: "1600", shutter: "1/50", aperture: "f/2.0", loc: "Event" },
  },
  {
    name: "IMG_6950.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6950.jpg",
    meta: { iso: "1600", shutter: "1/50", aperture: "f/2.0", loc: "Event" },
  },
  {
    name: "IMG_6976.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_6976.jpg",
    meta: { iso: "400", shutter: "1/320", aperture: "f/5.6", loc: "Walking" },
  },
  {
    name: "IMG_7026.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_7026.jpg",
    meta: { iso: "200", shutter: "1/500", aperture: "f/2.8", loc: "Sun" },
  },
  {
    name: "IMG_7048.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_7048.jpg",
    meta: { iso: "100", shutter: "1/1000", aperture: "f/1.8", loc: "Shade" },
  },
  {
    name: "IMG_7114.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_7114.jpg",
    meta: { iso: "800", shutter: "1/60", aperture: "f/4.0", loc: "Dusk" },
  },
  {
    name: "IMG_7141.JPG",
    type: "raw",
    url: "/images/Gallery/IMG_7141.jpg",
    meta: { iso: "1250", shutter: "1/30", aperture: "f/2.0", loc: "Night" },
  },
];