const base = import.meta.env.BASE_URL;

export const galleryFiles = [
  {
    name: "IMG_3006.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_3006.jpg`,
    meta: { iso: "100", shutter: "1/125", aperture: "f/11.0", loc: "City Architecture" },
  },
  {
    name: "IMG_3153.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_3153.jpg`,
    meta: { iso: "100", shutter: "1/250", aperture: "f/10.0", loc: "Palatial Gardens" },
  },
  {
    name: "IMG_3338.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_3338.jpg`,
    meta: { iso: "100", shutter: "1/1250", aperture: "f/6.3", loc: "Aerial Views" },
  },
  {
    name: "IMG_3360.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_3360.jpg`,
    meta: { iso: "200", shutter: "1/320", aperture: "f/8.0", loc: "Urban Heritage" },
  },
  {
    name: "IMG_3439.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_3439.jpg`,
    meta: { iso: "100", shutter: "1/400", aperture: "f/5.6", loc: "Architectural Detail" },
  },
  {
    name: "IMG_5775.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_5775.jpg`,
    meta: { iso: "100", shutter: "1/160", aperture: "f/5.6", loc: "Historic Streets" },
  },
  {
    name: "IMG_5860.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_5860.jpg`,
    meta: { iso: "100", shutter: "1/320", aperture: "f/5.6", loc: "Wildlife" },
  },
  {
    name: "IMG_6157.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6157.jpg`,
    meta: { iso: "800", shutter: "1/100", aperture: "f/5.6", loc: "Historic Monuments" },
  },
  {
    name: "IMG_6260.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6260.jpg`,
    meta: { iso: "100", shutter: "1/160", aperture: "f/6.3", loc: "Royal Heritage" },
  },
  {
    name: "IMG_6266.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6266.jpg`,
    meta: { iso: "1250", shutter: "1/50", aperture: "f/5.6", loc: "Lifestyle" },
  },
  {
    name: "IMG_6282.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6282.jpg`,
    meta: { iso: "1250", shutter: "1/800", aperture: "f/5.6", loc: "Culture & Dance" },
  },
  {
    name: "IMG_6470.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6470.jpg`,
    meta: { iso: "100", shutter: "1/1250", aperture: "f/6.3", loc: "Civic Monuments" },
  },
  {
    name: "IMG_6481.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6481.jpg`,
    meta: { iso: "100", shutter: "1/160", aperture: "f/6.3", loc: "Classical Sculpture" },
  },
  {
    name: "IMG_6539.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6539.jpg`,
    meta: { iso: "3200", shutter: "1/40", aperture: "f/5.6", loc: "Sacred Architecture" },
  },
  {
    name: "IMG_6540.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6540.jpg`,
    meta: { iso: "3200", shutter: "1/30", aperture: "f/5.6", loc: "Church Details" },
  },
  {
    name: "IMG_6647.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6647.jpg`,
    meta: { iso: "100", shutter: "1/400", aperture: "f/6.3", loc: "Urban Transit" },
  },
  {
    name: "IMG_6652.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6652.jpg`,
    meta: { iso: "100", shutter: "1/1000", aperture: "f/5.6", loc: "Public Memorials" },
  },
  {
    name: "IMG_6701.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6701.jpg`,
    meta: { iso: "3200", shutter: "1/50", aperture: "f/5.6", loc: "Baroque Interiors" },
  },
  {
    name: "IMG_6729.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6729.jpg`,
    meta: { iso: "100", shutter: "1/800", aperture: "f/7.1", loc: "Roofline Details" },
  },
  {
    name: "IMG_6940.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6940.jpg`,
    meta: { iso: "100", shutter: "1/400", aperture: "f/6.3", loc: "Urban Geometry" },
  },
  {
    name: "IMG_6944.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6944.jpg`,
    meta: { iso: "100", shutter: "1/400", aperture: "f/6.3", loc: "Sunset Cityscapes" },
  },
  {
    name: "IMG_6950.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6950.jpg`,
    meta: { iso: "100", shutter: "1/400", aperture: "f/5.6", loc: "Architecture at Dusk" },
  },
  {
    name: "IMG_6976.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_6976.jpg`,
    meta: { iso: "3200", shutter: "1/40", aperture: "f/5.6", loc: "Night Cityscapes" },
  },
  {
    name: "IMG_7026.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_7026.jpg`,
    meta: { iso: "3200", shutter: "1/40", aperture: "f/5.6", loc: "Heritage at Night" },
  },
  {
    name: "IMG_7048.jpg",
    type: "raw",
    url: `${base}images/Gallery/IMG_7048.jpg`,
    meta: { iso: "3200", shutter: "1/30", aperture: "f/5.6", loc: "Riverside Architecture" },
  },
];
