export const EMAIL = "theo.phan.quoc.huy@gmail.com";

export const SOCIALS = [
  { label: "GitHub", url: "https://github.com/Aer-3888", id: "GH-REP" },
  { label: "LinkedIn", url: "https://www.linkedin.com/in/theophanquochuy/", id: "LN-PRO" },
  { label: "Instagram", url: "https://www.instagram.com/phan.theo.huy/", id: "IG-VIS" },
];

// Language-neutral project structure. Translatable prose (metric, type,
// category, services, linkText, description, problem, approach, result, role,
// architecture) lives in src/locales/{en,fr}/projects.json keyed by id, and is
// merged in by the useProjects() selector. Titles, tags, and tools stay here.
export const PROJECTS = [
  {
    id: "01",
    title: "Waiki",
    year: "2025",
    img: `${import.meta.env.BASE_URL}images/optimized/waiki.webp`,
    imageCredit: "Photo: Théo Phan",
    url: "https://waikiup.com/",
    logoType: "website",
    offset: 120,
    tags: ["Flutter", "Dart", "Kotlin/Swift", "Firebase", "NFC"],
    tools: ["Android Studio", "Git", "GitHub Issues", "Kanban"],
  },
  {
    id: "09",
    title: "GardeFou",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/optimized/t1-injection-demo.webp`,
    url: "https://github.com/Aer-3888/GardeFou",
    logoType: "github",
    offset: 0,
    tags: ["Python", "RAG", "LLM Security", "Prompt Injection", "Chroma", "Ollama"],
    tools: ["FastAPI", "Streamlit", "sentence-transformers"],
  },
  {
    id: "03",
    title: "Plant Detection",
    year: "2025",
    img: `${import.meta.env.BASE_URL}images/optimized/plant_detection.webp`,
    url: "https://github.com/Aer-3888/Plant_detection",
    logoType: "github",
    offset: 0,
    tags: ["Python", "PyTorch", "EfficientNet", "YOLOv8", "Faster R-CNN", "OpenCV"],
    tools: ["Jupyter Notebook", "Kaggle API"],
  },
  {
    id: "10",
    title: "IAJ Evades",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/optimized/iaj_evades-gameplay.webp`,
    detailImg: `${import.meta.env.BASE_URL}images/optimized/iaj_evades-gameplay.gif`,
    url: "https://github.com/Aer-3888/iaj_evades",
    logoType: "github",
    offset: 0,
    tags: ["Rust", "Deep Q-Network", "Reinforcement Learning", "Neural Networks", "Rayon", "WebSockets"],
    tools: ["Cargo", "Axum", "React", "Recharts"],
  },
  {
    id: "04",
    title: "Notes INSA",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/optimized/notes-insa-collage.webp`,
    url: "https://codeberg.org/AerLight/Notes_insa",
    logoType: "codeberg",
    offset: -50,
    tags: ["Flutter", "Cloudflare Workers", "D1 Database", "Riverpod", "SQL"],
    tools: ["Android Studio", "Wrangler", "VS Code", "Git"],
  },
  {
    id: "05",
    title: "Intelligent File Manager",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/ph-file-manager.svg`, // Placeholder
    url: "#",
    logoType: "github",
    offset: -30,
    tags: ["C#", ".NET 10", "Avalonia", "SBERT", "CLIP", "Machine Learning"],
    tools: ["Avalonia", "Skia", "JetBrains Rider"],
  },
  {
    id: "02",
    title: "SafeWalk",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/safewalk-collage.png`,
    url: "https://github.com/Aer-3888/SafeWalk",
    logoType: "github",
    offset: 0,
    tags: ["Android Native", "Kotlin", "Cryptography", "BLE", "Foreground Services"],
    tools: ["Android Studio", "Android Keystore API"],
  },
  {
    id: "06",
    title: "Accountant Aut",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/optimized/accountant.webp`,
    url: "https://github.com/Aer-3888/accountant_aut",
    isClosedSource: true,
    logoType: "github",
    offset: 0,
    tags: ["C++", "Qt", "Google API", "OpenXLSX", "Ollama"],
    tools: ["CMake", "Git"],
  },
  {
    id: "07",
    title: "EDA Housing Market",
    year: "2025",
    img: `${import.meta.env.BASE_URL}images/optimized/eda_housing.webp`,
    url: "https://github.com/Aer-3888/EDA_Housing",
    logoType: "github",
    offset: 0,
    tags: ["Python", "Pandas", "Matplotlib", "Seaborn", "Folium"],
    tools: ["Jupyter Notebook", "Anaconda"],
  },
  {
    id: "08",
    title: "Portfolio",
    year: "2026",
    img: `${import.meta.env.BASE_URL}images/optimized/portfolio.webp`,
    url: "https://github.com/Aer-3888/portfolio",
    logoType: "github",
    offset: 0,
    tags: ["React", "JavaScript", "Tailwind CSS", "Framer Motion", "Lenis Scroll"],
    tools: ["Vite", "VS Code"],
  },
];
