export const NAV_ITEMS = [
  { label: "Projects", path: "/projects" },
  { label: "About", path: "/about" },
  { label: "Contact", path: "/contact" },
];

export const SOCIALS = [
  { label: "GitHub", url: "https://github.com/Aer-3888", id: "GH-REP" },
  { label: "LinkedIn", url: "https://www.linkedin.com/in/theophanquochuy/", id: "LN-PRO" },
  { label: "Instagram", url: "https://www.instagram.com/phan.theo.huy/", id: "IG-VIS" },
];

export const PROJECTS = [
  {
    id: "01",
    title: "Waiki",
    year: "2025",
    type: "Mobile Development",
    category: "Freelance",
    services: "Flutter - Mobile Development",
    img: `${import.meta.env.BASE_URL}images/waiki.png`,
    url: "https://waikiup.com/",
    linkText: "View Project Website",
    logoType: "website",
    offset: 0,
    description: "A digital wellness solution designed to combat social media addiction. Waiki introduces a physical barrier to digital habits, requiring users to physically scan a hardware device to unlock distracting apps, effectively breaking the 'infinite scroll' through behavioral pattern interrupts.",
    insight: "Breaking digital habits by introducing a physical friction point.",
    challenge: "Developing a reliable background NFC/QR scanning service that persists across iOS and Android power-saving modes.",
    tags: ["Flutter", "Dart", "Firebase", "Sqlite"],
    tools: ["Android Studio", "Git"],
    architecture: ["MVVM (Model-View-ViewModel)", "Feature-First (Layered by Feature)"],
  },
  {
    id: "02",
    title: "Portfolio",
    year: "2026",
    type: "Web Development",
    category: "Personal",
    services: "Front End - Animation - React",
    img: `${import.meta.env.BASE_URL}images/portfolio.png`,
    url: "https://github.com/Aer-3888/portfolio",
    linkText: "View Source Code",
    logoType: "github",
    offset: 120,
    description: "My personal portfolio website, focused on high-end animations and an immersive user experience using modern web technologies.",
    insight: "Creating a high-performance 'tunnel' navigation using vertical-to-horizontal scroll mapping.",
    challenge: "Optimizing complex Framer Motion transforms and SVG filters for 60FPS performance on mobile browsers.",
    tags: ["React", "JavaScript", "Tailwind CSS", "Framer Motion"],
    tools: ["Vite", "VS Code", "Lenis Scroll"],
    architecture: ["Component-Driven (Atomic Principles)", "Feature-First (Modular Page Structure)"],
  },
  {
    id: "03",
    title: "Plant Detection",
    year: "2025",
    type: "Computer Vision",
    category: "Personal",
    services: "Computer Vision - Python",
    img: `${import.meta.env.BASE_URL}images/plant_detection.png`,
    url: "https://github.com/Aer-3888/plant-detection",
    linkText: "View Repository",
    logoType: "github",
    offset: -50,
    description: "An object detection system trained on PlantDoc and PlantVillage datasets to identify plant species and diseases in real-time. Features comparative performance analysis between YOLO and Faster R-CNN using a ResNet-50 backbone.",
    insight: "Comparative study of real-time detection speed vs. classification accuracy.",
    challenge: "Training a custom YOLOv8 model on a diverse dataset with significant class imbalance and varying lighting conditions.",
    tags: ["Python", "PyTorch", "OpenCV"],
    tools: ["Jupyter Notebook", "Anaconda", "Docker"],
    architecture: ["YOLO (You Only Look Once)", "Faster R-CNN (Region-based CNN)", "ResNet-50 (Residual Backbone)"],
  },
  {
    id: "04",
    title: "Note insa",
    year: "2026",
    type: "Mobile Development",
    category: "Personal",
    services: "Flutter - Mobile Development - Riverpod",
    img: "https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=2670",
    url: "https://codeberg.org/AerLight/Notes_insa",
    linkText: "View Source Code",
    logoType: "codeberg",
    offset: -30,
    description: "A specialized mobile application designed to simplify academic life for INSA students. It provides a modern, intuitive interface for fetching and tracking grades, replacing legacy systems with a reactive dashboard. Built with Flutter and Riverpod, it ensures real-time data synchronization and a seamless user experience.",
    insight: "Redesigning the academic experience to fix the poor readability and fragmented UX of legacy school portals.",
    challenge: "Building a robust web scraper to bridge the gap between legacy school portals and a modern mobile UI.",
    tags: ["Flutter", "Dart", "Riverpod", "Scraping"],
    tools: ["Android Studio", "VS Code", "Git"],
    architecture: ["Riverpod (State Management)", "Stateless UI Approach", "Feature-First Architecture"],
  },
  {
    id: "05",
    title: "Accountant Aut",
    year: "2024",
    type: "Automation Tool",
    category: "Personal",
    services: "C++ - GUI Dashboard - Automation",
    img: `${import.meta.env.BASE_URL}images/accountant.png`,
    url: "https://github.com/Aer-3888/accountant_aut",
    linkText: "Closed Source Project",
    isClosedSource: true,
    logoType: "github",
    offset: 0,
    description: "A C++20 automation tool and interactive dashboard designed to synchronize accounting entries between Google Sheets and Sage 50. It provides a centralized interface for monitoring data flows, validating documentation on Google Drive, and programmatically mapping complex accounting codes.",
    insight: "Providing a high-visibility dashboard to monitor and manage the bridge between cloud spreadsheets and legacy accounting software.",
    challenge: "Developing a robust engine to handle complex accounting code mapping and entry validation as defined by the professional Quality Manual.",
    tags: ["C++", "Qt", "Google API", "OpenXLSX"],
    tools: ["CMake", "Git", "OpenXLSX"],
    architecture: ["Modular (Core/Network Architecture)", "Logic-Driven Mapping", "OAuth2 Authentication"],
  },
];
