// One-off / re-runnable image optimizer.
// Keeps every original in public/images and writes resized WebP derivatives into
// public/images/optimized (mirroring the folder layout), plus a small favicon set.
// Run with: npm run optimize:images
import sharp from "sharp";
import exifr from "exifr";
import { readdir, mkdir, stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const imagesDir = path.join(root, "public", "images");
const outDir = path.join(imagesDir, "optimized");
const publicDir = path.join(root, "public");

// Longest-edge caps per use. Project cards sit in a ~700px 4:3 frame, so these
// cover retina without shipping DSLR raws.
//
// Three derivatives per gallery photo. The contact sheet draws at roughly 120px,
// the half and third weight sequence frames at roughly 600px, and the full weight
// frames plus the per photo page at full width.
const GALLERY_WIDTHS = { thumb: 400, mid: 1200, full: 2000 };
const CARD_MAX = 1400;
const HERO_MAX = 1100; // me_.png is 796x1024, so this keeps it native.

async function toWebp(src, dest, maxEdge, quality) {
  await mkdir(path.dirname(dest), { recursive: true });
  const before = (await stat(src)).size;
  const info = await sharp(src)
    .rotate() // respect EXIF orientation
    .resize({ width: maxEdge, height: maxEdge, fit: "inside", withoutEnlargement: true })
    .webp({ quality })
    .toFile(dest);
  const after = (await stat(dest)).size;
  const kb = (n) => (n / 1024).toFixed(0);
  console.log(
    `  ${path.relative(imagesDir, src)}  ${kb(before)}KB -> ${kb(after)}KB  (${path.relative(imagesDir, dest)})`
  );
  // width and height come from the rendered output, so they already account for
  // the .rotate() above. Raw EXIF dimensions would call portrait shots landscape.
  return { before, after, width: info.width, height: info.height };
}

// EXIF stores shutter speed as a float. Photographers read fractions.
function formatShutter(seconds) {
  if (!seconds) return null;
  if (seconds >= 1) return `${Number(seconds.toFixed(1))}s`;
  return `1/${Math.round(1 / seconds)}`;
}

// Canon writes "Canon" as Make and "Canon EOS 250D" as Model, so a naive join
// produces "Canon Canon EOS 250D".
function formatCamera(make, model) {
  if (!model) return make ?? "";
  if (!make) return model;
  return model.startsWith(make) ? model : `${make} ${model}`;
}

async function readPhotoExif(src) {
  const raw = await exifr.parse(src, {
    pick: [
      "Make",
      "Model",
      "LensModel",
      "FocalLength",
      "FNumber",
      "ExposureTime",
      "ISO",
      "DateTimeOriginal",
    ],
  });
  if (!raw) throw new Error(`No EXIF found in ${src}`);
  return {
    camera: formatCamera(raw.Make?.trim(), raw.Model?.trim()),
    lens: raw.LensModel?.trim() ?? "",
    focal: raw.FocalLength ? `${Math.round(raw.FocalLength)}mm` : "",
    aperture: raw.FNumber ? `f/${Number(raw.FNumber.toFixed(1))}` : "",
    shutter: formatShutter(raw.ExposureTime) ?? "",
    iso: raw.ISO ?? 0,
    taken: raw.DateTimeOriginal ? raw.DateTimeOriginal.toISOString().slice(0, 10) : "",
  };
}

// Machine truth only. Curation lives in src/pages/Gallery/gallerySequence.js and
// is merged at module load, so re-running this script never touches copy.
async function writeGalleryData(photos) {
  const body = photos
    .map(
      (p) => `  {
    name: ${JSON.stringify(p.name)},
    src: {
      thumb: \`\${base}images/optimized/${p.src.thumb}\`,
      mid: \`\${base}images/optimized/${p.src.mid}\`,
      full: \`\${base}images/optimized/${p.src.full}\`,
    },
    width: ${p.width},
    height: ${p.height},
    exif: ${JSON.stringify(p.exif)},
  },`
    )
    .join("\n");

  const file = `// GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
// Run: npm run optimize:images
const base = import.meta.env.BASE_URL;

export const generatedPhotos = [
${body}
];
`;
  const dest = path.join(root, "src", "data", "gallery.generated.js");
  await mkdir(path.dirname(dest), { recursive: true });
  await writeFile(dest, file, "utf8");
  console.log(`  wrote src/data/gallery.generated.js (${photos.length} photos)`);
}

async function run() {
  let before = 0;
  let after = 0;
  const add = (r) => {
    before += r.before;
    after += r.after;
  };

  console.log("Gallery photos -> WebP x3 + EXIF:");
  const galleryDir = path.join(imagesDir, "Gallery");
  const generated = [];
  for (const f of (await readdir(galleryDir)).sort()) {
    if (!/\.(jpe?g|png)$/i.test(f)) continue;
    const src = path.join(galleryDir, f);
    const name = f.replace(/\.(jpe?g|png)$/i, "");
    const exif = await readPhotoExif(src);
    const srcs = {};
    let dims = null;
    for (const [key, width] of Object.entries(GALLERY_WIDTHS)) {
      const dest = path.join(outDir, "Gallery", `${name}-${width}.webp`);
      const info = await toWebp(src, dest, width, 78);
      add(info);
      srcs[key] = `Gallery/${name}-${width}.webp`;
      if (key === "full") dims = { width: info.width, height: info.height };
    }
    generated.push({ name, src: srcs, ...dims, exif });
  }
  await writeGalleryData(generated);

  console.log("Project cards -> WebP:");
  const cards = [
    "waiki.png",
    "portfolio.png",
    "plant_detection.png",
    "accountant.png",
    "eda_housing.png",
    "t1-injection-demo.png",
    "notes-insa-collage.png",
  ];
  for (const f of cards) {
    const dest = path.join(outDir, f.replace(/\.png$/i, ".webp"));
    add(await toWebp(path.join(imagesDir, f), dest, CARD_MAX, 80));
  }

  console.log("Hero cutout -> WebP:");
  add(await toWebp(path.join(imagesDir, "me_.png"), path.join(outDir, "me_.webp"), HERO_MAX, 82));

  console.log("Favicons (from me_icon.png):");
  const iconSrc = path.join(imagesDir, "me_icon.png");
  for (const size of [32, 64, 180]) {
    const name = size === 180 ? "apple-touch-icon.png" : `favicon-${size}.png`;
    const dest = path.join(publicDir, name);
    await sharp(iconSrc).resize(size, size, { fit: "cover" }).png({ compressionLevel: 9 }).toFile(dest);
    console.log(`  me_icon.png -> ${name} (${size}px, ${((await stat(dest)).size / 1024).toFixed(1)}KB)`);
  }

  console.log("Social preview card:");
  await generateOgImage();

  const mb = (n) => (n / 1024 / 1024).toFixed(1);
  console.log(`\nDerivatives total: ${mb(before)}MB originals -> ${mb(after)}MB WebP`);
}

// 1200x630 Open Graph card: hero cutout on the right, name + role on the paper canvas.
// Site tokens: paper #ffffff, ink #3f3f3f, stone #d3cec5, ash #686867, pebble #acacac.
// Text is rendered by librsvg via the SVG below; if Inter is not installed on this machine
// it falls back to a system sans, which is fine for a share card.
async function generateOgImage() {
  const W = 1200;
  const H = 630;
  const photo = await sharp(path.join(imagesDir, "me_.png"))
    .resize({ height: 600, fit: "inside" })
    .png()
    .toBuffer();
  const photoW = (await sharp(photo).metadata()).width;
  const photoLeft = W - photoW - 90;

  const svg = Buffer.from(
    `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
      <text x="90" y="300" font-family="Inter, Arial, sans-serif" font-size="96" font-weight="700" letter-spacing="-3" fill="#3f3f3f">Théo Phan</text>
      <rect x="93" y="332" width="70" height="3" fill="#d3cec5"/>
      <text x="90" y="392" font-family="Inter, Arial, sans-serif" font-size="30" fill="#686867">CS student, INSA Rennes</text>
      <text x="90" y="434" font-family="Inter, Arial, sans-serif" font-size="30" fill="#686867">AI + Full-Stack</text>
      <text x="90" y="565" font-family="Inter, Arial, sans-serif" font-size="21" letter-spacing="3" fill="#acacac">PORTFOLIO · 2026</text>
    </svg>`,
    "utf8"
  );

  const dest = path.join(publicDir, "og-preview.png");
  await sharp({ create: { width: W, height: H, channels: 4, background: "#ffffff" } })
    .composite([
      { input: photo, left: photoLeft, top: H - 600 },
      { input: svg, left: 0, top: 0 },
    ])
    .png()
    .toFile(dest);
  console.log(`  og-preview.png (${W}x${H}, ${((await stat(dest)).size / 1024).toFixed(1)}KB)`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
